services:
  app:
    image: daviddozer/front-office-ai-pre-rankings:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    restart: unless-stopped